backend:
  name: github
  repo: uu9/uu9.github.io
  branch: master
  site_domain: soranosro.tk

media_folder: "images/uploads"

collections:
  - name: "post" # Used in routes, e.g. /admin/collections/blog
    label: "Home Post" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.html
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}